# Generated by Django 3.0.4 on 2020-04-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_20200422_1337'),
        ('main', '0007_merge_20200422_1757'),
    ]

    operations = [
    ]
