# Generated by Django 3.0.4 on 2020-04-23 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20200422_2304'),
        ('main', '0010_merge_20200422_2305'),
    ]

    operations = [
    ]
